"use client";

import Link from "next/link";
import { ArrowRight, Clock3, Eye, FilePlus2, FolderOpen, MapPin } from "lucide-react";
import { useEffect, useState } from "react";
import { ClientShell } from "../../components/client-shell";
import { NoticeCenter } from "../../components/notice-center";

type LegalCase = { id: string; category: string; title: string; description: string; region: string | null; status: string; created_at: string; attention_mode: string | null; commune: string | null; view_count: number; proposal_count: number; };

function statusLabel(status: string) { return status === "open" ? "Disponible para abogados" : status === "matched" ? "En conversación" : status === "closed" ? "Cerrado" : "Borrador"; }

export default function ClientDashboardPage() {
  const [cases, setCases] = useState<LegalCase[]>([]);
  const [loading, setLoading] = useState(true);
  const [notice, setNotice] = useState("");
  async function loadCases() { try { const response = await fetch("/api/cases"); if (!response.ok) throw new Error(); const result = await response.json() as { cases: LegalCase[] }; setCases(result.cases); } finally { setLoading(false); } }
  useEffect(() => { void loadCases(); }, []);
  async function closeCase(id: string) { setNotice(""); try { const response = await fetch("/api/cases", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, action: "close" }) }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error || "No pudimos cerrar el caso."); setNotice("Caso cerrado. Ya no aparecerá disponible para nuevos abogados."); await loadCases(); } catch (error) { setNotice(error instanceof Error ? error.message : "No pudimos cerrar el caso."); } }
  return <ClientShell><div className="portal-page-heading"><div><p className="eyebrow">Área personal</p><h1>Tu orientación legal, en orden.</h1><p>Desde aquí puedes publicar casos y cerrarlos cuando ya encontraste abogado.</p></div><Link className="portal-primary-button" href="/publicar-caso"><FilePlus2 size={17} /> Publicar un caso</Link></div>{notice && <p className="save-confirmation">{notice}</p>}<section className="client-summary"><article><span className="metric-icon"><FolderOpen size={20} /></span><p>Casos publicados</p><strong>{loading ? "-" : cases.length}</strong><small>Visibles solo para profesionales habilitados</small></article><article><span className="metric-icon"><Clock3 size={20} /></span><p>Esperando propuestas</p><strong>{loading ? "-" : cases.filter((item) => item.status === "open").length}</strong><small>Casos publicados sin abogado elegido</small></article><article><span className="metric-icon"><Eye size={20} /></span><p>Propuestas recibidas</p><strong>{loading ? "-" : cases.reduce((total, item) => total + (item.proposal_count || 0), 0)}</strong><small>Revisa y compara antes de aceptar</small></article></section><section className="portal-panel client-cases" id="mis-casos"><div className="panel-title"><div><p className="eyebrow">Mis solicitudes</p><h2>Casos publicados</h2></div>{cases.length > 0 && <span className="content-count">{cases.length} {cases.length === 1 ? "caso" : "casos"}</span>}</div>{loading ? <p className="client-loading">Cargando tus solicitudes...</p> : cases.length === 0 ? <div className="client-empty"><span className="empty-mark"><FilePlus2 size={25} /></span><h2>Aún no has publicado un caso.</h2><p>Elige una materia y cuéntanos brevemente qué necesitas resolver.</p><Link className="portal-primary-button" href="/publicar-caso">Publicar mi primer caso <ArrowRight size={17} /></Link></div> : <div className="client-case-list">{cases.map((legalCase) => <article className="client-case-row" key={legalCase.id}><div><p className="eyebrow">{legalCase.category}</p><h3>{legalCase.title}</h3><p>{legalCase.description}</p><small><MapPin size={13} /> {legalCase.commune || legalCase.region || "Atención por definir"} · {legalCase.attention_mode || "Modalidad por definir"} · <Eye size={13} /> {legalCase.view_count} vistas · {legalCase.proposal_count || 0} propuestas</small></div><div className="client-case-actions"><Link className="portal-primary-button" href={`/cliente/caso/?id=${encodeURIComponent(legalCase.id)}`}>Ver avance y propuestas</Link><span className={`case-state ${legalCase.status}`}>{statusLabel(legalCase.status)}</span>{legalCase.status !== "closed" && <button className="portal-outline-button" onClick={() => closeCase(legalCase.id)}>Cerrar caso</button>}</div></article>)}</div>}</section><NoticeCenter /></ClientShell>;
}
